# Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx4096M

# Gradle
org.gradle.jvmargs=-Xmx4096M -Dfile.encoding=UTF-8

# Enable various build optimizations
org.gradle.configuration-cache=true               # Enable configuration cache for faster subsequent builds
org.gradle.configuration-cache-problems=warn      # Warn about issues with the configuration cache
org.gradle.configureondemand=true                 # Configure projects on demand to reduce configuration time
org.gradle.caching=true                           # Enable build caching to reuse task outputs and speed up builds
org.gradle.parallel=true                          # Enable parallel execution of tasks to leverage multi-core processors
