package dev.kodex.agentic.code.reviewer.core

import dev.kodex.agentic.code.reviewer.agents.BaseAgent
import dev.kodex.agentic.code.reviewer.tools.git.diff.DiffChunkPipeline

class ReviewCoordinator(
    private val agents: List<BaseAgent>,
    private val contextBuilder: ContextBuilder
) {
    suspend fun review(diff: String): String {
        val pipeline = DiffChunkPipeline()
        val chunks = pipeline.process(diff)
        val results = chunks.flatMap { chunk ->
            val enriched = contextBuilder.enrich(chunk)
            agents.map { agent ->
                agent.run(enriched)
            }
        }

        return format(results)
    }

    private fun format(results: List<String>): String {
        return """
# AI Code Review

${results.joinToString("\n\n")}

---
Generated by Koog Review System
"""
    }
}
