build:
  maxIssues: 0
  excludeCorrectable: false

config:
  validation: true
  warningsAsErrors: false
  checkExhaustiveness: false

processors:
  active: true
  exclude:
    - 'DetektProgressListener'

console-reports:
  active: true
  exclude:
    - 'ProjectStatisticsReport'
    - 'ComplexityReport'
    - 'NotificationReport'
    - 'FindingsReport'
    - 'FileBasedFindingsReport'

output-reports:
  active: true

comments:
  active: true
  AbsentOrWrongFileLicense:
    active: false
  DeprecatedBlockTag:
    active: true
  EndOfSentenceFormat:
    active: true
    endOfSentenceFormat: '([.?!][ \t\n\r\f<])|([.?!:]$)'
  KDocReferencesNonPublicProperty:
    active: true
  OutdatedDocumentation:
    active: true

complexity:
  active: true
  CognitiveComplexMethod:
    active: true
    threshold: 30
  ComplexCondition:
    active: true
    threshold: 4
  ComplexInterface:
    active: true
    threshold: 10
  CyclomaticComplexMethod:
    active: true
    threshold: 15
  LargeClass:
    active: true
    threshold: 600
  LongMethod:
    active: true
    threshold: 60
  LongParameterList:
    active: true
    functionThreshold: 8
    constructorThreshold: 8
  TooManyFunctions:
    active: true
    thresholdInFiles: 20
    thresholdInClasses: 20
    thresholdInInterfaces: 10

coroutines:
  active: true

empty-blocks:
  active: true

exceptions:
  active: true

formatting:
  active: true
  android: false
  autoCorrect: true
  Indentation:
    active: true
    indentSize: 4
  MaximumLineLength:
    active: true
    maxLineLength: 120
  ImportOrdering:
    active: true
  FinalNewline:
    active: true
  NoWildcardImports:
    active: true
  NoUnusedImports:
    active: true
  NoTrailingSpaces:
    active: true
  StringTemplate:
    active: true
  NoSemicolons:
    active: true

naming:
  active: true
  ClassNaming:
    classPattern: '[A-Z][a-zA-Z0-9]*'
  FunctionNaming:
    functionPattern: '[a-z][a-zA-Z0-9]*'
  TopLevelPropertyNaming:
    constantPattern: '[A-Z][_A-Z0-9]*'
    propertyPattern: '[a-z][A-Za-z0-9]*'
    privatePropertyPattern: '_?[a-z][A-Za-z0-9]*'

performance:
  active: true

potential-bugs:
  active: true

style:
  active: true

  MagicNumber:
    active: true
    ignoreNumbers: [ '-1', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '200', '400', '401', '403', '404', '500', '8080' ]
    ignoreHashCodeFunction: true
    ignorePropertyDeclaration: true
    ignoreConstantDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
    ignoreAnnotation: true
    ignoreNamedArgument: true
    ignoreEnums: true

  ReturnCount:
    active: true
    max: 4

  WildcardImport:
    active: true
    excludeImports:
      - 'java.util.*'
