build:
  maxIssues: 0

config:
  validation: true
  warningsAsErrors: false

processors:
  active: true

console-reports:
  active: true

output-reports:
  active: true

comments:
  active: true
  AbsentOrWrongFileLicense:
    active: false

complexity:
  active: true
  ComplexCondition:
    threshold: 4
  CyclomaticComplexMethod:
    threshold: 15
  LongMethod:
    threshold: 60
  LongParameterList:
    threshold: 8
  TooManyFunctions:
    thresholdInFiles: 20
    thresholdInClasses: 20
    thresholdInInterfaces: 20

coroutines:
  active: true

empty-blocks:
  active: true

exceptions:
  active: true

formatting:
  active: true
  android: false
  autoCorrect: true
  AnnotationOnSeparateLine:
    active: false
  ChainWrapping:
    active: true
  CommentSpacing:
    active: true
  EnumEntryNameCase:
    active: false
  Filename:
    active: true
  FinalNewline:
    active: true
  ImportOrdering:
    active: true
  Indentation:
    active: true
    indentSize: 4
  MaximumLineLength:
    active: true
    maxLineLength: 120
  ModifierOrdering:
    active: true
  NoBlankLineBeforeRbrace:
    active: true
  NoConsecutiveBlankLines:
    active: true
  NoEmptyClassBody:
    active: true
  NoLineBreakAfterElse:
    active: true
  NoLineBreakBeforeAssignment:
    active: true
  NoMultipleSpaces:
    active: true
  NoSemicolons:
    active: true
  NoTrailingSpaces:
    active: true
  NoUnusedImports:
    active: true
  NoWildcardImports:
    active: true
  PackageName:
    active: true
  ParameterListWrapping:
    active: true
  SpacingAroundColon:
    active: true
  SpacingAroundComma:
    active: true
  SpacingAroundCurly:
    active: true
  SpacingAroundKeyword:
    active: true
  SpacingAroundOperators:
    active: true
  SpacingAroundParens:
    active: true
  SpacingAroundRangeOperator:
    active: true
  StringTemplate:
    active: true

naming:
  active: true
  ClassNaming:
    classPattern: '[A-Z][a-zA-Z0-9]*'
  FunctionNaming:
    functionPattern: '[a-z][a-zA-Z0-9]*'
  TopLevelPropertyNaming:
    constantPattern: '[A-Z][_A-Z0-9]*'
    propertyPattern: '[a-z][A-Za-z0-9]*'
    privatePropertyPattern: '_?[a-z][A-Za-z0-9]*'

performance:
  active: true

potential-bugs:
  active: true

style:
  active: true
  ForbiddenComment:
    active: false
  MagicNumber:
    active: true
    ignoreNumbers:
      - '-1'
      - '0'
      - '1'
      - '2'
      - '200'
      - '400'
      - '401'
      - '403'
      - '404'
      - '500'
      - '8080'
    ignoreHashCodeFunction: true
    ignorePropertyDeclaration: true
    ignoreConstantDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
    ignoreAnnotation: true
    ignoreNamedArgument: true
    ignoreEnums: true
  ReturnCount:
    max: 4
  UnnecessaryAbstractClass:
    active: false
  WildcardImport:
    active: true
