sources:
  github_actions:
    enabled: true
    paths:
      - .github/workflows/*.yml
    files: [ ]
  gitlab_ci: { }
  circleci: { }
  bitbucket: { }
pipeline:
  steps:
    - name: assemble
      enabled: true
      cmd: ./gradlew assemble --no-daemon
      timeout_seconds: 1200
      pass_codes:
        - 0
      warn_codes: [ ]
      diff_bounded:
        enabled: true
        patterns:
          - '**/*.kt'
          - '**/*.java'
          - '**/*.kts'
          - build.gradle*
    - name: lint
      enabled: true
      cmd: JAVA_HOME="/Volumes/ADATASD810/Library/Toolbox/Android Studio.app/Contents/jbr/Contents/Home" ./gradlew detekt --no-daemon
      timeout_seconds: 1200
      pass_codes:
        - 0
      warn_codes: [ ]
      diff_bounded:
        enabled: true
        patterns:
          - '**/*.kt'
          - '**/*.java'
          - '**/*.kts'
          - build.gradle*
    - name: test & coverage
      enabled: true
      cmd: ./gradlew test jvmTest jsTest koverXmlReport koverVerify --no-daemon
      timeout_seconds: 1800
      pass_codes:
        - 0
      warn_codes: [ ]
      diff_bounded:
        enabled: true
        patterns:
          - '**/*.kt'
          - '**/*.java'
          - '**/*.kts'
          - build.gradle*
    - name: benchmark
      enabled: true
      cmd: ./gradlew benchmark --no-daemon
      timeout_seconds: 1800
      pass_codes:
        - 0
      warn_codes: [ ]
      diff_bounded:
        enabled: true
        patterns:
          - '**/*.kt'
          - '**/*.java'
          - '**/*.kts'
          - build.gradle*

execution:
  fail_fast: true
  verbose: true
  env:
    GRADLE_OPTS: -Dorg.gradle.daemon=false
  working_dir: .
  retry:
    max_attempts: 1
    delay_seconds: 0

report:
  path: docs/cicd
  include_logs: true
  include_timing: true
  include_diff_analysis: true
